### ISSUE TITLE
Reliance on pcntl_fork

### ISSUE THREAD

**Issue by HelloGrayson** [d11wtq/boris#1]
Unable to run Boris because of a reliance on a non default extension PCNTL. 

```
PHP Fatal error:  Call to undefined function pcntl_fork() in boris/lib/Boris.php on line 38
```

Would be great if this extension could be avoided, other-words it should be listed as a dependency in the README with directions on how to recompile PHP with PCNTL enabled.

**Comment by RichardBradley** [comment]
> I'll leave this ticket open in case somebody can come up with an approach that doesn't rely on the ability to fork.

One alternative to `pcntl_fork` is to "recreate" the current PHP environment by starting a new PHP in which you load all the same code and update all global state to match the current state. PHPUnit does this when you configure `runTestInSeparateProcess`, to avoid a dependency on `fork`.
See https://github.com/sebastianbergmann/phpunit/issues/909
and [`/src/Framework/TestCase.php:783`](https://github.com/sebastianbergmann/phpunit/blob/a1b5663a426b85854e97dce080a3546907836d5a/src/Framework/TestCase.php#L783)

This is somewhat fragile, and more likely to work for something like PHPUnit which is running from PHP source files, than for Boris which is running from user input. Further, if there is any code which has side-effects, it may get re-run on each pseudo-fork.
