### ISSUE TITLE
Packagist no longer has different version based of tags

### ISSUE THREAD

**Issue by markcameron** [d11wtq/boris#121]
Visiting the packagist page https://packagist.org/packages/d11wtq/boris for this package only shows the dev-master version, even though there is a multitude of tags in the Git repository. Is it normal that they have disappeared? Do they need to be resynced?

It's breaking third party packages that I depend on in my build process.

Many thanks

**Comment by sergiocastrovale** [comment]
I'm having the exact same problem and I'm deploying a huge app right now ...

**Comment by dhotson** [comment]
Hmm, sounds strange.. I just tried clicking the "update" button on packagist. Can you try it now?

**Comment by markcameron** [comment]
Yeah that's better they are all back now. Building correctly.

Thanks
