### ISSUE TITLE
Dumping out current environment?

### ISSUE THREAD

**Issue by girvo** [d11wtq/boris#73]
Hey there!

Love `boris`, it makes PHP development and exploration of a codebase an absolute dream. The one thing I feel like that its missing is a feature that may not even be possible to implement, but I thought I'd ask regardless.

How difficult would it be to be able to export/dump the PHP that has been typed into the REPL? Say, function definitions and the like? Not necessarily expressions per se (although to be honest, even just a straight "transcript" dump would be brilliant), but function, class and method definitions that have been typed in. 

Perhaps even a way of defining "This is a new session for this environment, start recording what I'm doing" and the "End that session and export the code out to a PHP file". The reason I'd love something like that is it would enable *true* interactive development through the REPL itself, rather close to how Lisp REPLs are implemented. 

I'm going to take a poke through Boris' code and have a look at whether it'd be possible anyway, but I thought I'd ask!

**Comment by dhotson** [comment]
Hey Josh, thanks for the question. Sorry about the wait.

Boris currently keeps track of all the commands you've entered into a `~/.boris_history` file. You could possibly grab your last few typed commands from there. Maybe not quite what you're looking for—but might be ok.

I know iPython has some great features similar to what you mentioned:
http://ipython.org/ipython-doc/rel-0.10.2/html/interactive/tutorial.html#source-code-handling-tips

.. I think these kinds of features could be good additions to boris. Would you be keen to have a go at contributing? :)
