### ISSUE TITLE
Reloading Boris

### ISSUE THREAD

**Issue by girvo** [d11wtq/boris#74]
Hey there,

Would love to see a feature to reload boris while inside. I'm going to see if I can write it myself, but was curious about what key combo I should bind it to. I'm leaning towards Ctrl + R. 

The feature itself will basically just do the same as exiting and restarting, to bring in the code changes to the environment you've required with `boris -r`. Nothing fancy, basically just doing the same as Ctrl + D except instead of exiting entirely, it starts up again.

I couldn't find much else in the issues list, although my search-fu is weak, has this been discussed anywhere?

Keep up the awesome work :)

Josh

**Comment by sserbin** [comment]
@d11wtq 

> You should be able to basically have $this->reload(); do a pcntl_exec(); with the appropriate program command, thus replacing that forked child with a completely fresh instance of Boris.

Wouldn't that leave the original master process hanging around/becoming a zombie? You can probably make some cleanup in a new Boris instance but that sounds a bit hacky - am I missing something?
